#!/bin/bash
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-002/rroman_base_1112151618.relax.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-003/rroman_based_1201181020.relax.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-004/Easrec-1203081428.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-005/Easrec-1204251118.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-006/Easrec-1205161103.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-007/Easrec-1210111237.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-008/Easrec-1210241214_ff5.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-009/Easrec-1211141135.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-010/Easrec-1212131343.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-011/Easrec-1301100920.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-012/Easrec-1302211010.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-013/Easrec-1303070851.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-014/Easrec-1303281004.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-015/Easrec-1304120917.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-016/Easrec-1305101059.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-017/Easrec-1306051006.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-018/Easrec-1309031324.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-019/Easrec-1309250948.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-020/Easrec-1310090913.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-021/Easrec-1310231053.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-023/Easrec-1401081136.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-025/Easrec-1404021424.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-026/Easrec-1404171032.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-027/Easrec-1404301455.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-028/Easrec_140522-1023.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-029/Easrec_ic_exp-029_140625-0938.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-030/Easrec_ic_exp-030_140710-0936.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-031/Easrec_ic_exp-031_140903-1009.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-032/Easrec_ic_exp-032_141008-1041.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-033/Easrec_ic_exp-033_141022-1049.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-034/Easrec_ic_exp-034_150305-1102.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-035/Easrec_ic_exp-035_150401-1034.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-036/Easrec_ic_exp-036_150429-1437.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-038/Easrec_sciexp-69novakova_150831-1027.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-039/Easrec_sciexp-seeg039_150916-0931.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-040/Easrec_sciexp-seeg040_151001-1120.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-041/Easrec_sciexp-seeg041_151014-1106.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-042/Easrec_sciexp-seeg042_151104-0827.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-043/Easrec_sciexp-seeg043_151111-0838.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-045/Easrec_sciexp-seeg045_160114-1023.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-046/Easrec_sciexp-seeg046_160127-0828.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-047/Easrec_sciexp-seeg047_160218-1105.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-048/Easrec_sciexp-seeg048_160323-1036.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-049/Easrec_sciexp-seeg049_160422-1002.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-050/Easrec_sciexp-seeg050_160518-0841.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-051/Easrec_sciexp-seeg051_160921-1102.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-052/Easrec_sciexp-seeg052_161005-1058.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-053/Easrec_sciexp-seeg053_161019-1020.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-054/Easrec_sciexp-seeg054_161118-1138.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-056/Easrec_sciexp-seeg056_170208-1005.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-057/Easrec_sciexp-seeg057_170222-1033.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-058/Easrec_sciexp-seeg058_170308-1121.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-059/Easrec_sciexp-seeg059_170427-1101.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-060/Easrec_sciexp-seeg060_170517-0848.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-061/Easrec_sciexp-seeg061_170531-1038.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-063/Easrec_sciexp-seeg063_170906-0811.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-066/Easrec_sciexp-seeg066_171018-0957.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-067/Easrec_sciexp-seeg067_171101-0842.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-068/Easrec_sciexp-seeg068_171115-0921.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-069/Easrec_sciexp-seeg069_180110-0945.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-070/Easrec_sciexp-seeg070_180214-1029.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-071/Easrec_sciexp-seeg071_180228-0914.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-072/Easrec_sciexp-seeg072_180314-1245.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-073/Easrec_sciexp-seeg073_180328-1051.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-074/Easrec_sciexp-seeg074_180418-0920.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-075/Easrec_sciexp-seeg075_180517-0938.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-076/Easrec_sciexp-seeg076_180530-1015.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-077/Easrec_sciexp-seeg077_180815-1045.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-078/Easrec_sciexp-seeg078_180905-0911.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-079/Easrec_sciexp-seeg079_180919-0847.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-080/Easrec_sciexp-seeg080_181010-0846.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-081/Easrec_sciexp-seeg081_181031-0844.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-082/Easrec_sciexp-seeg082_181114-0844.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-083/Easrec_sciexp-seeg083_190109-0852.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-084/Easrec_sciexp-seeg084_190123-0843.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-085/Easrec_sciexp-seeg085_190220-0857.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-087/Easrec_sciexp-seeg087_190403-1030.mefd
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/envelopes_runfile.py -f /media/vojtech/DATADRIVE2/data/seeg-090/Easrec_sciexp-seeg090_190515-0914.mefd
