#!/bin/bash
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-023/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-046/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-002/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-003/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-004/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-005/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-006/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-007/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-008/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-009/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-010/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-011/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-012/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-013/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-014/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-015/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-016/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-017/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-018/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-019/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-020/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-021/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-025/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-026/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-027/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-028/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-029/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-030/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-031/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-032/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-033/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-034/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-035/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-036/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-038/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-039/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-040/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-041/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-042/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-043/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-045/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-047/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-048/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-049/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-050/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-051/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-052/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-053/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-054/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-056/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-057/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-058/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-059/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-060/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-061/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-063/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-066/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-067/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-068/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-069/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-070/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-071/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-072/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-073/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-074/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-075/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-076/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-077/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-078/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-079/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-080/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-081/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-082/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-083/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-084/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-085/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-087/
ts /home/vojtech/pyenv/bin/python /home/vojtech/Nextcloud/python/UHFO_Pavel/scripts/pdmatrix_runfile.py -f /media/vojtech/DATADRIVE4/hfo_envelopes/seeg-090/
